Create dev branch
koomekevo/space_travellers_hub pull request #26
Opened 2022-01-25 09:16 UTC by koomekevo

This Pull Request has been created under dev branch to achieve the following:
- Create React App.
- Edit initial README.md information.
- Add Stylelint and EsLint.

2022-01-27 16:13 UTC, Meltrust requested changes
Hi @mohamedelshamy55, 


There are some issues that you still need to work on to go to the next project but you are almost there!

## You did a great job here team, the project works flawlessly! However, in order to comply with the requirements, we need to make an addition and some small changes.  Kindly please look at my comments below 👇 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-27 16:13 UTC, Meltrust commented on README.md
- [ ] OPTIONAL: If you add a screenshot of your project to your readme, your project documentation will look a lot better ✔️

2022-01-27 16:13 UTC, Meltrust commented on package.json
>      "@testing-library/react": "^12.1.2",
- [ ] Please, kindly add tests for your app.  The only test I could find is the one that comes with `create-react-app`.

![image](https://user-images.githubusercontent.com/57421823/151382989-feec0fcc-b248-499e-8fe7-79f7129c8bb1.png)

![image](https://user-images.githubusercontent.com/57421823/151383398-bd94c6ef-270b-41de-9e6b-7527233fa2f7.png)


That way, you will ensure the scalability of your app while making sure it still works as intended.

2022-01-27 16:13 UTC, Meltrust commented on src/pages/MissionsList.js
> +            }
- [ ] For this particular project, the React conditional render syntax is required for conditionally displaying both the Rockets and the Missions:

![image](https://user-images.githubusercontent.com/57421823/151388114-547dfc15-0380-44e6-b274-b7f7fbe510bb.png)

Don't worry! I'll show you how!! 💪 💪 

This is an example:

![image](https://user-images.githubusercontent.com/57421823/151388576-018db458-f6d7-4bfc-b0f9-a90dd7768f4f.png)

Another example with a kind of "if/else" scheme:

![image](https://user-images.githubusercontent.com/57421823/151396150-0479bcef-bb3b-44d2-b1a7-e696d222f7d2.png)


The rule is that if the condition on the left of the `&&` is true, the action of the right will be run. 💪 

Now that you know how to do it kindly please implement this syntax to your missions and rockets conditional rendering (i.e. for the "reserved" badge, the "join" badge, etc). ✔️

2022-01-27 16:13 UTC, Meltrust commented on src/pages/RocketsCards.js
> +            )}
_(This is the second iteration of my last comment about the conditional rendering syntax.  Copied it here just for reference.  It's exactly the same requirement as with the rockets)._

- [ ] For this particular project, the React conditional render syntax is required for conditionally displaying both the Rockets and the Missions:

![image](https://user-images.githubusercontent.com/57421823/151388114-547dfc15-0380-44e6-b274-b7f7fbe510bb.png)

Don't worry! I'll show you how!! 💪 💪 

This is an example:

![image](https://user-images.githubusercontent.com/57421823/151388576-018db458-f6d7-4bfc-b0f9-a90dd7768f4f.png)

Another example with a kind of "if/else" scheme:

![image](https://user-images.githubusercontent.com/57421823/151396150-0479bcef-bb3b-44d2-b1a7-e696d222f7d2.png)


The rule is that if the condition on the left of the `&&` is true, the action of the right will be run. 💪 

Now that you know how to do it kindly please implement this syntax to your missions and rockets conditional rendering (i.e. for the "reserved" badge, the "join" badge, etc). ✔️

2022-01-28 12:32 UTC, elyor-doniyorov approved these changes
Hi @koomekevo and @mohamedelshamy55, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## STATUS APPROVED ✅ 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-28 12:40 UTC, merged